### ISSUE TITLE
 "class ColorVar Settings::UI::mainColor" (?mainColor@UI@Settings@@3VColorVar@@A)	xhook WoW_1.13	

### ISSUE THREAD

**Issue by Mrasd741** [maikel233/xhook_wowclassic_TBC#4]
sorry for my stupid question ， i  include all Folder  and    include detours.x64 and detours.lib,syelog.lib 。 But the compiler still reports an error。what can  i  do ？
![@%7H0MF`UJ@%~A`28IQIH$3](https://user-images.githubusercontent.com/78683252/130359301-4bcacf38-d5a6-4872-ad80-c614d30134f7.png)

**Comment by maikel233** [comment]
Check the project path settings you can also try #include dllmain, menu and settings in those 3 files.
