### ISSUE TITLE
how to dump  lua func 

### ISSUE THREAD

**Issue by Mrasd741** [maikel233/xhook_wowclassic_TBC#5]
hi, In your project, you found the base addresses of all Lua functions. I tried to do this, but found that wow is encrypted and IDA can't find all functions. I run wow and dump the memory to the file. I find that it is still the same. I don't have a definite breakthrough direction. Can you roughly describe the method of dump Lua function?

**Comment by maikel233** [comment]
Dump wow:
[Ownedcore Dump wow with x64 scyla](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/640683-how-dump-wow-memory.html)

Offsets:
[Ownedcore offsets](https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-bots-programs/wow-memory-editing/952729-tbc-classic-2-5-1-39640-a.html)

What i did at the start was comparing a fresh wow classic dump with the 18179 mac build this was was time consuming and i wouldn't recommend it.

What you can try...
1. Download the mac build on ownedcore and go to your desired lua func [x ref] it and it will probably list a script_Something?
2. Look at my script dump list and go to that address in the live dump and compare it. Dont forget to rebase in ida to 0x00

**Comment by Mrasd741** [comment]
thanks for your help,Now I get the Lua function address, onlly a little different from yours. It should be the version problem.

**Comment by maikel233** [comment]
yes
