### ISSUE TITLE
Hello, why is it stuck here

### ISSUE THREAD

**Issue by l511407563** [maikel233/xhook_wowclassic_TBC#7]
After successful startup
![Image 12](https://user-images.githubusercontent.com/25783291/148568103-50d27baa-9660-4336-8881-cb065acdbea6.png)
![Image 11](https://user-images.githubusercontent.com/25783291/148568141-1b8d58c0-9d68-42c9-a37a-09d147a28b14.png)
Keep typing: [+] Present Hook called by first time
Nothing appears in the game

**Comment by maikel233** [comment]
start wow -> Settings -> set your directx to 11 or 11legacy?

**Comment by l511407563** [comment]
> start wow -> Settings -> set your directx to 11 or 11legacy?

Is it this? I set this
![Image 2](https://user-images.githubusercontent.com/25783291/148589037-05d3faaa-bb89-43ef-bacc-b0cfa337875b.png)
![Image 1](https://user-images.githubusercontent.com/25783291/148589057-710db1cd-623a-402b-8a19-37d4a399ae31.png)

Could it be because I didn't download the files you said?
I don't know where to find mmaps and vmtiles.
Is it because of this?
![Image 4](https://user-images.githubusercontent.com/25783291/148589243-2c2a8ce8-f665-4da1-8d5b-1e486248a9d4.png)


I printed here, the value of ret is -2147467262.
![photo_2022-01-08_00-19-29](https://user-images.githubusercontent.com/25783291/148589602-41f3ad92-5d1a-49d9-873f-29827f1c3cae.jpg)

Please help me, thank you!

**Comment by maikel233** [comment]
I already gave you a answer. start WORLD OF WARCRAFT -> MENU->SETTINGS -> DIRECTX SET IT TO: DIRECTX11 OR DX11_LEGACY

**Comment by micenote** [comment]
> 

我用vs2019一直无法正常编译。你怎么编译成功的，能给说说不？
